# http 服务
server:
  app_name: cxs
  http_port: 8081
  enable_pprof: true
  env: dev

# 日志
log:
  level: debug
  format: json
  log_dir: ./logs # 日志存放目录，确保路径与Filebeat监控路径一致
  filename_prefix: gin-gorm-frame
  max_size: 100 # 日志文件最大大小，单位MB
  max_backups: 30 # 旧日志文件最大保存数量
  max_age: 30 # 日志文件最大保存时间，单位天
  compress: true # 是否压缩日志文件
  console_output: true # 是否打印到控制台


# db 数据库
db:
  default_alias: default
  connections:
    - db1:
      alias: default
      dialect: mysql
      user: root
      password: 123456
      host: 127.0.0.1
      port: 3306
      database: gin-gorm-frame
      charset: utf8mb4
      show_mysql: true
      max_open: 20
      max_idle: 5

    - db2:
      alias: db2
      dialect: mysql
      user: root
      password: 123456
      host: 127.0.0.1
      port: 3306
      database: gin-gorm-frame
      charset: utf8mb4
      show_mysql: true
      max_open: 20
      max_idle: 5

# redis
redis:
  default_alias: default
  connections:
    - redis1:
      alias: default
      addr: 127.0.0.1:6479
      password: ""
      db_index: 15
      max_idle: 2
      max_open: 10

    - redis2:
      alias: session
      addr: 127.0.0.1:6479
      password: ""
      db_index: 14
      max_idle: 2
      max_open: 10
